default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: carsspot_development

test:
  <<: *default
  database: carsspot_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  connect_timeout: 20
  checkout_timeout: 15
  reaping_frequency: 10