# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: carsspot_development

test:
  <<: *default
  database: carsspot_test

production:
  <<: *default
  database: d7rnsgf5of0mub
  username: uciof0kqlarmc9
  password: pe66156de0d85a0f11b180dcaa4c93467270202de6ae5983c849090d7457111b1
  host: c5p86clmevrg5s.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com
  port: 5432
  sslmode: require
  connect_timeout: 30
